### PR TITLE
minor bugfixes + code redundancy

### PR DESCRIPTION
**Pull request by aditi989**
- improved `lyrics` command;
- defined a const embed for empty queue error;
- fixed aliases of `leave` command;

### CODE REVIEW

**Review by code-chaser — CHANGES_REQUESTED** [review]
- You are on fire, bug-hunter!
- Just one thing, in `music.py` @ `line 970` change `read more` back to `see results from GoogleSearch`, I can merge it then.

Thanks!

**Comment by aditi989** [comment]
Oops, thanks for spotting that out, I'll correct that.

**Comment by aditi989** [comment]
Done!
Please check.

**Review by code-chaser — APPROVED** [review]
Merging PR 🎉

**Pull request merged**
